name       : purple-hangouts
version    : 2020.11.05
release    : 10
source     :
    - git|https://github.com/EionRobb/purple-hangouts.git : efa7a53e2db4087a1590850423aa16b380bfbbd5
license    : GPL-3.0-or-later
component  : network.im
summary    : Hangouts Plugin for libpurple/Pidgin
description: |
    A replacement prpl for Hangouts in Pidgin/libpurple to support the proprietary protocol that Google uses for its Hangouts service. So far it supports all the fun things that aren't part of the XMPP interface, such as Group Chats, synchronised history between devices and SMS support via Google Voice.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libprotobuf-c)
    - pkgconfig(purple)
build      : |
    %make
install    : |
    %make_install
