name       : purple-hangouts
version    : 2019.03.03
release    : 5
source     :
    - https://bitbucket.org/EionRobb/purple-hangouts/get/ea746fe.tar.gz : 38cb5c374f661b908d90e7190a4b0ea8cb54fd061ff387be05382fa456376636
license    : GPL-3.0-or-later
component  : network.im
summary    : Hangouts Plugin for libpurple/Pidgin
description: |
    A replacement prpl for Hangouts in Pidgin/libpurple to support the proprietary protocol that Google uses for its Hangouts service. So far it supports all the fun things that aren't part of the XMPP interface, such as Group Chats, synchronised history between devices and SMS support via Google Voice.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libprotobuf-c)
    - pkgconfig(purple)
build      : |
    %make
install    : |
    %make_install
